apiVersion: v1
kind: Service
metadata:
  name: fifth-node-app
  namespace: fifth-node-app
  labels:
    app: fifth-node-app
    backstage.io/kubernetes-id: fifth-node-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: fifth-node-app
